### ISSUE TITLE
SLParseError.getSourceLocation() raises IllegalArgumentException

### ISSUE THREAD

**Issue by numberpi** [graalvm/simplelanguage#47]
Parsing the erroneous code snippet
`function main`
in SL causes an internal error when calling `SLParseError.getSourceLocation()`.

```
java.lang.IllegalArgumentException: column out of range
	at com.oracle.truffle.api.source.Source.createSection(Source.java:592)
	at com.oracle.truffle.sl.parser.SLParseError.getSourceLocation(SLParseError.java:67)
        ...
```

Caused because offending symbol is `EOF` and `charPositionInLine + 1` is `14`:
https://github.com/graalvm/simplelanguage/blob/b30c3efa9c30b2e7d0dac9d44bc346c570789a85/language/src/main/java/com/oracle/truffle/sl/parser/SimpleLanguageParser.java#L161

**Comment by numberpi** [comment]
sorry, duplicate of #40 ... opened by myself -.-
